---
- hosts: ec-4610-05-lab-rack4:
  become: yes
  tasks:
    - name: restore ports.conf
      copy:
        src=save/{{ansible_hostname}}/ports.conf
        dest=/etc/cumulus/ports.conf
    - name: restore interfaces
      copy:
        src=save/{{ansible_hostname}}/etc/network/interfaces
        dst=/etc/network/interfaces
        
