---
- hosts: 10.50.1.115
  become: yes
  tasks:
    - name: restore ports.conf
      copy:
        src: save/{{ansible_hostname}}/ports.conf
        dest: /etc/cumulus/ports.conf
    - name: restore interfaces
      copy:
        src: save/{{ansible_hostname}}/interfaces
        dest: /etc/network/interfaces
        
